services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ny_taxi
    ports:
      - "5433:5432"
    volumes:
      - vol-pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"  # Changed from 8080 to 5050
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin

  ingest:
    build: .
    container_name: data_ingest
    volumes:
      - .:/app
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/ny_taxi
    depends_on:
      - db

volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmin_data:
    name: vol-pgadmin_data